### ISSUE TITLE
does not detect abnormal behavior

### ISSUE THREAD

**Issue by bmabir17** [ShoupingShan/Abnormal-behavior-Detection#3]
I have tried to run the detector demo as per your instructions. But it only shows the objects that are found in the image, does not shows the Red mask that you have showed for the fighting image. Do i have to train it with fighting videos to get the red masked area? or does it detect it out of the box?

**Comment by ShoupingShan** [comment]
Sorry for missing your issue such a long time (I did not receive any prompts), I do not pay attention to this issue until today. According to your question, There are two probable reasons. First, The SVM model result was not suitable (I just trained it in several data) for your problem so that you can train your own data to suit your situation. Second, maybe I upload the wrong `out.txt` after several update, because someone before run this demo well and she can also detect fight behavior.
